### PR TITLE
refactor: parsing log into generalized utility function

### PR DESCRIPTION
**Pull request by tiendn**
### Description:
This PR introduces a generalized utility function for parsing event logs from transaction receipts. 

**Changes:**
- **Generalized Function Implementation**: Implemented a new utility function `parseEventLogs` that abstracts the log parsing logic. This function takes a transaction receipt, a contract factory, and an event name as parameters, and returns an array of parsed logs that match the specified event.
- **Refactoring Existing Code**: Replaced the existing log parsing code in the `EvmIsmCreator` class with calls to the new `parseEventLogs` function. This change affects how logs are parsed when deploying domain routing ISMs.

### CODE REVIEW

**Comment by paulbalaji** [comment]
Appreciate the work here! Just noting we've done this refactor for our next major CLI release, you can see it here: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/e0f226806ef261d848def5c424c8af3936b9e79f/typescript/sdk/src/utils/logUtils.ts#L4

**Comment by tiendn** [comment]
> Appreciate the work here! Just noting we've done this refactor for our next major CLI release, you can see it here:
> 
> https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/e0f226806ef261d848def5c424c8af3936b9e79f/typescript/sdk/src/utils/logUtils.ts#L4

hm, I just checked out from main, any issues with sync here ?

**Comment by paulbalaji** [comment]
> hm, I just checked out from main, any issues with sync here ?

not a sync issue here, more of an FYI that we are going to merge the `cli-2.0` branch back into `main` soon so will be closing this PR in favour of the existing implementation there

**Comment by tiendn** [comment]
Thank you! 
I'll close this PR.

**Pull request closed without merging**
