### PR TITLE
Sdk 1.1.0

### PR DESCRIPTION
**Pull request by tkporter**
### Description

_What's included in this PR?_

### Drive-by changes

_Are there any minor or drive-by changes also included?_

### Related issues

- Fixes #[issue number here]

### Backward compatibility

_Are these changes backward compatible?_

Yes
No

_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this infra tooling?_

None
Yes

### Testing

_What kind of testing have these changes undergone?_

None
Manual
Unit Tests

### CODE REVIEW

**Review by yorhodes — APPROVED** [review]

**Comment by asaj** [comment]
@tkporter too late to squeeze in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1669

**Comment by tkporter** [comment]
@asaj ah yeah sorry I already shipped 1.1.0. I'll merge this, feel free to ship 1.1.1

**Comment by tkporter** [comment]
Seems like I first need to update the submodules, opened https://github.com/hyperlane-xyz/hyperlane-app-template/pull/42 and https://github.com/hyperlane-xyz/hyperlane-token/pull/32

**Comment by asaj** [comment]
@tkporter FYI you don't need to block on PRs to these other repos if you point the gitmodules to different branches

**Pull request merged**
