### PR TITLE
Update moonbeam reorg period

### PR DESCRIPTION
**Pull request by nambrot**
### Description

Updates the moonbeam reorg period.

- Already updated the docs page
- Deployed this to mainnet2 as well
- Communicated the recommendation to validators

### Drive-by changes

- none

### Related issues

- Fixes https://github.com/hyperlane-xyz/issues/issues/417

### Backward compatibility

Yes

_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this infra tooling?_

None

### Testing

_What kind of testing have these changes undergone?_

None

### CODE REVIEW

**Review by jmrossy — APPROVED** [review]

**Review by tkporter — APPROVED** [review]
can you do moonbasealpha too?

**Comment by tkporter** [comment]
Or actually did we say we're cool with reorgs on testnet

**Comment by jmrossy** [comment]
> did we say we're cool with reorgs on testnet
@tkporter Less cool now that testnet eth markets are popping up

**Comment by tkporter** [comment]
ooh great point @jmrossy

**Pull request merged**
