### PR TITLE
optimising Create2Factory.deployedAddress

### LINKED ISSUE #1882: Create2Factory deployedAddress function optimization
@tkporter I recommend utilizing the scratch space and temporarily the free memory pointer slot to compute the create2 address as it is a more efficient method. 
In addition to the savings on execution, this reduces deployment size by 360 bytes for a simple contract. That's a lot of bytecode

### PR DESCRIPTION
**Pull request by chainchampion**
### Description
This PR optimises the deployedAddress function in Create2Factory by utilising the scratch space and temporarily the free memory pointer slot to compute the create2 address.

### Related issues

- Fixes #1882 

### Backward compatibility

_Are these changes backward compatible?_

Yes

_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this infra tooling?_

None

### CODE REVIEW

**Review by asaj — COMMENTED** [review]
Thanks for the suggestion!

This is a cool optimization, but I'm afraid I don't think the optimization is worth the readability lost by introducing assembly, as this function is called relatively infrequently (i.e. when hyperlane is deployed to a new chain)

**Comment by chainchampion** [comment]
> Thanks for the suggestion!
> 
> This is a cool optimization, but I'm afraid I don't think the optimization is worth the readability lost by introducing assembly, as this function is called relatively infrequently (i.e. when hyperlane is deployed to a new chain)

Hey @asaj , I thought that hyperlane must be using this create2 Factory for InterchainAccounts too, where there's a need to calculate the ICA address on the fly. I read ICA's code thoroughly, and it looks like, in the case of Interchain accounts, openzepplin's create2 implementation is being used to calculate the ICA address at runtime, which already incorporates the same optimization... 
Therefore, I agree that this optimization is not required for the readability of the code.

**Comment by chainchampion** [comment]
@asaj
What is the use of this `Create2Factory` when you are using OZ's create2 in other parts of your code?

**Comment by asaj** [comment]
We use Create2Factory occasionally to deploy core contracts with consistent addresses

**Comment by asaj** [comment]
> Hey @asaj , I thought that hyperlane must be using this Create2Factory for InterchainAccounts too, where there's a need to calculate the ICA address on the fly.

Yeah perfectly reasonable assumption, and optimizations would definitely make more sense if that was the case

**Pull request closed without merging**
