### PR TITLE
Migrate router test

### LINKED ISSUE #2757: Migrate router tests from hardhat to forge
This is the last remaining hardhat unit test suite and we are not instrumenting coverage following https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2752

### PR DESCRIPTION
**Pull request by ottbunn**
### Description

Updating the router tests from hardhat to forge.

### Drive-by changes
no

### Related issues
- Fixes #2757 

### Backward compatibility
No

### Testing
((changing the testing itself))

### CODE REVIEW

**Comment by ottbunn** [comment]
Hi 👋🏻 I'm new to the code space and solidity development in general, when working on the pr I noticed that the coverage report of the `Router.sol`  is not reflected with the testing, guessing it's because we're mainly using `TestRouter.sol` and inheriting `Router.sol`. wonder if there's better way to observe the coverage or if I'm missing something. Thanks!!

**Comment by yorhodes** [comment]
> Hi 👋🏻 I'm new to the code space and solidity development in general, when working on the pr I noticed that the coverage report of the `Router.sol` is not reflected with the testing, guessing it's because we're mainly using `TestRouter.sol` and inheriting `Router.sol`. wonder if there's better way to observe the coverage or if I'm missing something. Thanks!!

Hey @ottbunn ! This is a mighty fine contribution for being new to coding :)

I should have clarified in the ticket that we are making contract changes on the `v3` feature branch

**Comment by ottbunn** [comment]
@yorhodes thanks!!! umm I see so I should translate the hardhat test file `solidity/test/router.test.ts` on the v3 branch and make pr to the v3 branch right?

**Comment by yorhodes** [comment]
> so I should translate the hardhat test file `solidity/test/router.test.ts` on the v3 branch and make pr to the v3 branch right?

Yep, change the base of this PR to the `v3` branch and fix any conflicts

**Comment by ottbunn** [comment]
Um, looks like it'll be better to start over from the v3 branch directly. I'll close this pr and start over

**Comment by avious00** [comment]
@ottbunn sorry for the hassle with the `v3` branch!

**Comment by ottbunn** [comment]
no worries!! thanks!! a good experience for me to learn to clarify questions before start 🙂

**Pull request closed without merging**
