### PR TITLE
feat: add zksync deployment

### LINKED ISSUE #2487: zkSync + zkLink deployment
### Context

https://zksync.io/ is a major zk L2. While it promises EVM compatibility, [contract deployment](https://era.zksync.io/docs/reference/architecture/contract-deployment.html) is non-standard which has prevented folks from deploying there so far. 

zkLink is built on zkSync's stack and is likely the first of more zkSync Elastic (rollup framework) chains we'll encounter. We're open to a short term contract-only deployment, but will likely want to fix this in our tooling.

### Bounty
This issue tracks the work necessary to get a Hyperlane deployment up and running. To complete this ticket, you should have a PR to hyperlane-deploy which you used to get a deployment up there.

### Reward
- This bounty is $1000

### PR DESCRIPTION
**Pull request by NOOMA-42**
### Description

add zksync deployment

### Drive-by changes

1. I add the deployment script outside of existing tooling per the [discord discussion](https://discord.com/channels/935678348330434570/1192150985565556776/1193757282236903455) 
2. The newest `zksync-ethers` require `ether@6` which is not used by hyperlane, I used `zksync-ethers@5` instead.
3. Deployment list: 
    - [ ] Mailbox
    - [ ] Multisig
    - [ ] ISM
    - [ ] IGP
    - [ ] test recipient 

### Related issues

fixed #2487

### Backward compatibility

Not compatible with existing SDK:
1. Bunch of zksync custom package: zksync-ethers, hardhat-zksync-deploy, hardhat-zksync-node, hardhat-zksync-solc, hardhat-zksync-verify, zksync-contracts
2. zkSync `Wallet` doesn't inherit `Signer` 
3. `Signer` in ethers is an abstract class, whereas `Signer` in zkSync inherit adapted version of `jsonrpc signer`. Compared to Original `Signer` in ether is an abstract class, `wallet` used by MetaMask injection and `jsonrpcSigner` inherit `signer`. zkSync ethers don't use Abstract Signer from etherjs, the reason is [answered here](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/291#discussioncomment-8324611)
4. There're `L1Signer` and `L2Signer` in zkSync SDK, those are different.
5. Other differences can refer to [official doc](https://docs.zksync.io/build/sdks/js/features.html)

**TODO**
- [ ] https://github.com/zkSync-Community-Hub/zksync-developers/discussions/348
- [ ] https://github.com/zkSync-Community-Hub/zksync-developers/discussions/346

### Testing

Deployment:
* bridge eth to zksync sepolia with native bridge tx-bridge

### CODE REVIEW

**Comment by avious00** [comment]
@NOOMA-42 let yorke and i know when this is ready for review!

**Comment by NOOMA-42** [comment]
Update:
I'm still working on it. The differences between ethers and zkSync-ethers are more substantial than I initially imagined.

**Comment by NOOMA-42** [comment]
I have to close this PR per the discussion here https://discord.com/channels/935678348330434570/1035311559993462944/1211983448126922767

> It's unlikely that we can merge this into monorepo anytime soon

**Comment by NOOMA-42** [comment]
I have to close this PR per the discussion here https://discord.com/channels/935678348330434570/1035311559993462944/1211983448126922767

> It's unlikely that we can merge this into monorepo anytime soon

**Pull request closed without merging**
