### PR TITLE
feat: weighted ISM factory deployments

### PR DESCRIPTION
**Pull request by aroralanuk**
### Description

- Adding staticMerkleRootWeightedMultisigIsmFactory and staticMessageIdWeightedMultisigIsmFactory verification outputs

### CODE REVIEW

**Review by paulbalaji — COMMENTED** [review]
is there a corresponding registry PR?

**Comment by ltyu** [comment]
> is there a corresponding registry PR?

https://github.com/hyperlane-xyz/hyperlane-registry/pull/158

**Review by yorhodes — APPROVED** [review]
lgtm
please populate PR description

**Comment by aroralanuk** [comment]
Looking at the contracts deployed, many of them are not verified. And the `scripts/verify.ts` script uses `--buildArtifactPath ` which I can't find in the repo, is there another way of verifying the contracts post-deployment?

**Pull request merged**
