### PR TITLE
Make helloworld and token submodules

### PR DESCRIPTION
**Pull request by yorhodes**
### Description

- Makes `typescript/token` and `typescript/helloworld` git submodules

### Backward compatibility

Yes

### Testing

Unit Tests

### CODE REVIEW

**Comment by nambrot** [comment]
I did this implicitly in my PR and should have called it out but I upgraded the OZ library that included the breaking API changes and IIUC, this will "overwrite it" since i haven't ported the changes over to the token repo yet?

**Comment by yorhodes** [comment]
> I did this implicitly in my PR and should have called it out but I upgraded the OZ library that included the breaking API changes and IIUC, this will "overwrite it" since i haven't ported the changes over to the token repo yet?

the sub module is a reference to the ported branch on the token repo

**Comment by nambrot** [comment]
Ahh I missed that

**Comment by nambrot** [comment]
Should we track updating that to `main` somewhere?

**Comment by yorhodes** [comment]
> Should we track updating that to `main` somewhere?

updated to main

**Pull request merged**
