### PR TITLE
Split hardhat and foundry-testing

### PR DESCRIPTION
**Pull request by nambrot**
### Description

Splits the CI job for hopefully better performance

### CODE REVIEW

**Review by yorhodes — APPROVED** [review]
nice, big devops guy

**Comment by nambrot** [comment]
Be the change you want to see

**Comment by asaj** [comment]
FYI we will conflict https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1662

**Comment by asaj** [comment]
@nambrot should we close? I don't think this saves us more than a few seconds

**Comment by asaj** [comment]
@nambrot I'm going to close, speak now or forever hold your peace

**Comment by nambrot** [comment]
agreed

**Pull request closed without merging**
